apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: europe-central2-docker.pkg.dev/my-project-417912/my-docker-registry/myapp-with-template
        ports:
        - containerPort: 8888
        resources:
          requests:
            cpu: 200m

